name: Publish to NPM

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check if version has changed
      id: check
      run: |
        LOCAL_VERSION=$(node -p "require('./package.json').version")
        NPM_VERSION=$(npm view salakala version 2>/dev/null || echo "0.0.0")
        if [ "$LOCAL_VERSION" != "$NPM_VERSION" ]; then
          echo "Version changed from $NPM_VERSION to $LOCAL_VERSION"
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "Version unchanged"
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Use Node.js 20.x
      if: steps.check.outputs.version_changed == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
    
    - name: Install dependencies
      if: steps.check.outputs.version_changed == 'true'
      run: npm ci
    
    - name: Build
      if: steps.check.outputs.version_changed == 'true'
      run: npm run build
    
    - name: Publish to NPM
      if: steps.check.outputs.version_changed == 'true'
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 