name: Tests

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GOOGLE_TEST_SERVICE_KEY:
        required: true
      GOOGLE_CLOUD_PROJECT:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true
      BW_CLIENTID:
        required: true
      BW_CLIENTSECRET:
        required: true
      BW_PASSWORD:
        required: true
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install KeePassXC
      run: |
        sudo apt-get update
        sudo apt-get install -y keepassxc
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Setup Google Cloud credentials
      run: |
        echo '${{ secrets.GOOGLE_TEST_SERVICE_KEY }}' > /tmp/google-credentials.json
    
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v2

    - name: Install Bitwarden CLI
      run: |
        npm install -g @bitwarden/cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/google-credentials.json
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
        BW_CLIENTID: ${{ secrets.BW_CLIENTID }}
        BW_CLIENTSECRET: ${{ secrets.BW_CLIENTSECRET }}
        BW_PASSWORD: ${{ secrets.BW_PASSWORD }}
        BW_SERVER: https://vault.bitwarden.eu
        AWS_REGION: us-east-1
      run: npm test 
